### ISSUE TITLE
Documentation updates (minor)

### ISSUE THREAD

**Issue by tim-oe** [switchdoclabs/SDL_Pi_SkyWeather2#2]
there's some minor issues with file names not matching actual code.

sudo python3 testWeatherSensors.py
file not present but
sudo python3 testWirelessSensors.py
seems to be the correct one

the different py scripts referenced have different dependencies so you need to run through each one
to get all deps working.

I didn't use the provisioned sd card and wanted to only use pi lite to minimize disk usage.

I've got the following project where i've been documenting my setup.
https://github.com/tim-oe/SkyWeather2
the init.sh script has all the needed steps i did, so far.
https://github.com/tim-oe/SkyWeather2/blob/main/src/bin/init.sh

great project, it's the only weather station i could find where a can actually collect my own data.

**Comment by switchdoclabs** [comment]
Thank you!  Added to the SkyWeather2 Bug List.

BP
